[package]
name = "cloudivs-common"
version = "0.0.1"
authors = ["lizhiyong2000 <lizhiyong2000@gmail.com>"]
readme = "../README.md"
edition = "2018"

[features]
nightly = []

[lib]
path = "lib.rs"

[dependencies]
failure = "0.1.1"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
parking_lot = { version = "0.10", features = [] }
nom = "5.1.1"
time = "0.1"
